import "./globals.css";
import { Alex_Brush, PT_Sans } from "next/font/google";
import { Providers } from "./providers";

const pt_sans = PT_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-ptSans",
});

const alex_brush = Alex_Brush({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-alexBrush",
});

export const metadata = {
  title: "The Venue",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${pt_sans.variable} ${alex_brush.variable}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
